In [181]:
import numpy as np

In [182]:
l=[1,2,3,4]

In [183]:
arr=np.array(l)
arr

array([1, 2, 3, 4])

In [184]:
type(arr)

numpy.ndarray

In [185]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [186]:
np.asarray(l)

array([1, 2, 3, 4])

In [275]:
b=np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [188]:
print(type(b))

<class 'numpy.matrix'>


In [189]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [190]:
a=np.array(l)

In [191]:
c=a

In [192]:
a

array([1, 2, 3, 4])

In [193]:
c

array([1, 2, 3, 4])

In [194]:
c[0]=200
c

array([200,   2,   3,   4])

In [195]:
a

array([200,   2,   3,   4])

In [196]:
d=np.copy(a)
d

array([200,   2,   3,   4])

In [197]:
d[0]=300
d

array([300,   2,   3,   4])

In [198]:
a

array([200,   2,   3,   4])

In [199]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [200]:
np.fromfunction(lambda i,j: i==j, (2,2))

array([[ True, False],
       [False,  True]])

In [201]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [202]:
np.fromfunction(lambda i,j : i*j, (3,5))

array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 4.],
       [0., 2., 4., 6., 8.]])

In [203]:
iterable=(i*i for i in range(5))

In [204]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [205]:
np.fromstring("4445 555", sep=" ")

array([4445.,  555.])

In [206]:
l1=[[1,2,3,4],[5,6,7,8]]

In [207]:
arr1=np.array(l1)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [208]:
arr1.ndim

2

In [209]:
type(arr1)

numpy.ndarray

In [210]:
arr1.size

8

In [211]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [212]:
arr3=arr1.shape
arr3

(2, 4)

In [213]:
type(arr3)

tuple

In [268]:
arr1.dtype

dtype('int32')

In [214]:
arr4=np.array([(1,4.5,3),(4.7,3.2,5)])
arr4

array([[1. , 4.5, 3. ],
       [4.7, 3.2, 5. ]])

In [215]:
type(arr4)

numpy.ndarray

In [216]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [217]:
np.arange(2.3,5.4)

array([2.3, 3.3, 4.3, 5.3])

In [218]:
list(np.arange(2.3,8.6,.4))

[2.3,
 2.6999999999999997,
 3.0999999999999996,
 3.4999999999999996,
 3.8999999999999995,
 4.299999999999999,
 4.699999999999999,
 5.1,
 5.499999999999999,
 5.899999999999999,
 6.299999999999999,
 6.699999999999998,
 7.099999999999999,
 7.499999999999999,
 7.899999999999999,
 8.299999999999997]

In [219]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [220]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [221]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [222]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [223]:
on=np.ones((5,3,2))

In [224]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [225]:
on*2

array([[[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]]])

In [226]:
on+3

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [227]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [228]:
np.empty((3,2))

array([[1. , 4.5],
       [3. , 4.7],
       [3.2, 5. ]])

In [229]:
np.empty((3,2))

array([[1. , 4.5],
       [3. , 4.7],
       [3.2, 5. ]])

In [230]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [231]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [232]:
np.logspace(2,4,10, base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [245]:
arr5=np.random.randn(3,4)
arr5

array([[-0.49352425,  0.39995374, -0.57973275, -2.85430552],
       [-0.29243055, -0.28570027, -0.3771051 , -1.43875865],
       [ 0.07271783, -1.29270073, -1.33022919, -0.2384635 ]])

In [246]:
import pandas as pd

In [247]:
pd.DataFrame(arr5)

0         1         2         3
0 -0.493524  0.399954 -0.579733 -2.854306
1 -0.292431 -0.285700 -0.377105 -1.438759
2  0.072718 -1.292701 -1.330229 -0.238464

In [250]:
arr6=np.random.randint(1,100,(3,4))
arr6

array([[ 3, 50, 26, 78],
       [ 3, 88, 58, 35],
       [66, 98, 46, 47]])

In [255]:
df=pd.DataFrame(np.random.randint(1,100,(3,4))).to_csv("randomfile.csv")


In [256]:
pd.DataFrame(np.random.randint(1,100,(3,4)))

0   1   2   3
0  78  52  25  60
1  90  55  46  27
2  25  45  78  65

In [266]:
arr.reshape(6,344444444)

ValueError: cannot reshape array of size 12 into shape (6,344444444)